export const ADDING_MOVIE = "ADDING_MOVIE";
export const ADDING_MOVIE_SUCCESS = "ADDING_MOVIE_SUCCESS";
export const ADDING_MOVIE_FAIL = "ADDING_MOVIE_FAIL";

export const EDITING_MOVIE = "EDITING_MOVIE";
export const EDITING_MOVIE_SUCCESS = "EDITING_MOVIE_SUCCESS";
export const EDITING_MOVIE_FAIL = "EDITING_MOVIE_FAIL";

export const REMOVING_MOVIE = "REMOVING_MOVIE";
export const REMOVING_MOVIE_SUCCESS = "REMOVING_MOVIE_SUCCESS";
export const REMOVING_MOVIE_FAIL = "REMOVING_MOVIE_FAIL";